// AUTO-GENERATED by scripts/write-build-info.mjs.
// Overwritten on every build. Do not edit by hand.

export const BUILD_DATE_ISO = '2026-05-14T22:10:45.651Z'
export const BUILD_DATE_DISPLAY = 'May 14, 2026, 5:10 PM'
export const BUILD_VERSION = '05.14.2026'
